### ISSUE TITLE
Some tests crash

### ISSUE THREAD

**Issue by fjlc-73** [sns3/sns3-satellite#56]
Trying to run some simulations specifically for LEO satellites. I get the following message for example:

javi@javi-virtual-machine:~/Documents/ns-3-dev$ ./ns3 run sat-mobility-example.cc 
msg="Forward regeneration must be network when using constellations", file=/home/javi/Documents/ns-3-dev/contrib/satellite/helper/satellite-helper.cc, line=261
NS_FATAL, terminating
terminate called without an active exception
Command 'build/contrib/satellite/examples/ns3-dev-sat-mobility-example-optimized' died with <Signals.SIGABRT: 6>.

List of tests that fail:
839 of 863 tests passed (839 passed, 0 skipped, 0 failed, 24 crashed, 0 valgrind errors)
List of CRASHed tests:
    contrib/satellite/examples/sat-constellation-example
    contrib/satellite/examples/sat-dama-http-sim-tn9
    contrib/satellite/examples/sat-dama-onoff-sim-tn9
    contrib/satellite/examples/sat-dama-sim-tn9
    contrib/satellite/examples/sat-dama-verification-sim
    contrib/satellite/examples/sat-essa-example
    contrib/satellite/examples/sat-group-example
    contrib/satellite/examples/sat-gw-handover-example
    contrib/satellite/examples/sat-handover-example
    contrib/satellite/examples/sat-iot-example
    contrib/satellite/examples/sat-link-budget-example
    contrib/satellite/examples/sat-logon-example
    contrib/satellite/examples/sat-lora-example
    contrib/satellite/examples/sat-mobility-beam-tracer
    contrib/satellite/examples/sat-mobility-position-generator
    contrib/satellite/examples/sat-ncr-example
    contrib/satellite/examples/sat-per-packet-if-sim-tn9
    contrib/satellite/examples/sat-ra-sim-tn9
    contrib/satellite/examples/sat-ra-sim-tn9-comparison
    contrib/satellite/examples/sat-regeneration-collisions-example
    contrib/satellite/examples/sat-regeneration-example
    contrib/satellite/examples/sat-rtn-system-test-example
    contrib/satellite/examples/sat-training-example
    contrib/satellite/examples/sat-vhts-example

**Comment by bastientauran** [comment]
Hi,

Can you tell me what commits you are using for ns-3 and the three modules (satellite, traffic and magister-stats) ? This will allow me to reproduce the error. Can you also tell me which build profile you are using (optimized, debug or other) ?

sat-mobility-example is an old example, not used anymore and not included in the test suite. I can reproduce this error for this one, and I will investigate. If you want to use mobility or constellation scenarios, you can look at sat-constellation-example or sat-handover-example.

For all the other tests, they all pass for me. Are you sure you setup the submodule in the satellite repository ?

**Comment by Furkkaya** [comment]
> Hi,
> 
> Can you tell me what commits you are using for ns-3 and the three modules (satellite, traffic and magister-stats) ? This will allow me to reproduce the error. Can you also tell me which build profile you are using (optimized, debug or other) ?
> 
> sat-mobility-example is an old example, not used anymore and not included in the test suite. I can reproduce this error for this one, and I will investigate. If you want to use mobility or constellation scenarios, you can look at sat-constellation-example or sat-handover-example.
> 
> For all the other tests, they all pass for me. Are you sure you setup the submodule in the satellite repository ?

For which version and commit are all the tests passed? I'm using NS 3.42 dev module commit 202c72e and mine some of the examples and tests are failed or crashed. 

![Image](https://github.com/user-attachments/assets/a7cb7f91-3788-4031-aa08-34fbd27c42cd)

I don't know if I'm making a mistake while installing and building.

**Comment by Furkkaya** [comment]
I've been trying to download SNS3 properly for about 4-5 months, can you please tell me step by step how to download it? It doesn't matter what version, as long as it works. I really don't know what to do, please someone help me. Either I have a problem while building, or the examples don't work after I build successfully. I'm going crazy.

**Comment by Kniyl** [comment]
Hi @Furkkaya 

First of all, please do not hijack others issues. If you're still having installations problems, keep it to #54 . Also, try to make your posts efficient for others to help you. A picture is neither indexable nor searchable let alone when it's a diagonal shot of your screen.

Getting back to your problem, I already told you to use the tried and tested `git clone --recursive -b dev https://github.com/sns3/sns3-satellite.git satellite` inside the `contrib` folder of your ns3 install. Did you do it ? What was the output ? What was the content of the data folder ?

Please answer in #54

**Comment by bastientauran** [comment]
@fjlc-73,

First I pushed a new commit on the dev branch, this should fix the sat-mobility-example.cc file.

To help us understand the other issues, you can launch the test suite with these additional arguments: "-v -t log". Please send me on test format the stdout content, and log.txt file

**Comment by Furkkaya** [comment]
Hello, I encountered such a problem today, I reinstalled NS3 and tried it but the problem did not change. Do you think the problem is caused by the VM?

![Image](https://github.com/user-attachments/assets/8b284b12-3634-4329-a311-21d94bcfaa47)

**Comment by bastientauran** [comment]
Hello @Furkkaya,

Did the compilation step succeeded ? It seems unlikely that it succeeded as all the tests failed.
Can you perform a fresh install: first run "./ns3 clean" and then send me the result of the following steps:

- "./ns3 configure --build-profile=optimized --enable-examples --enable-tests"
- "./ns3 build"
- "./test.py -v"

Additionally, how musc ressource did you allocate to your VM (CPU, RAM, etc.) and what OS are you using on it ?

Thank you

**Comment by wakaay** [comment]
Hi bro @bastientauran
today, this problem still exists, I will show u the results 

- "./ns3 configure --build-profile=optimized --enable-examples --enable-tests"

<img width="612" height="390" alt="Image" src="https://github.com/user-attachments/assets/324ef5e6-f421-475d-8ebd-4b1ef51b9692" />

if any dependency I didn't install?

**Comment by bastientauran** [comment]
The features that are not installed are not mandatory to run SNS-3, thus this configuration is fine. However make sure you have the packet `libxml2-dev` installed to run some SNS-3 tests and examples.

To help you more, I need some details. Can you run one single crashing example (`./ns3 run <example_name>`) and send me the output ?

**Comment by wakaay** [comment]
hey @bastientauran 
really thanks for your help. Now I have run these examples successfully! Thanks for your remind, I found that I didn't execute the command`git submodule --init --recursive` correctly 
But I also have one example which is also crashed.  

<img width="791" height="248" alt="Image" src="https://github.com/user-attachments/assets/d1b0a9aa-3e6e-4e48-a578-c5090708f4a4" />

I have run this single crashed example:

<img width="804" height="124" alt="Image" src="https://github.com/user-attachments/assets/49ad3206-60db-4d02-addc-52208097785c" />

**Comment by bastientauran** [comment]
Your program has been killed, probably by the OS. Maybe your machine does not have enough RAM: this example is very ressource consuming, and needs several Go of RAM.
If you do not have a lot of RAM installed, you can ignore this crashing example.
